---
- name: "Application / Blender / Prerequisite / Prepare package managers"
  vars:
    sys_repository:
      prepare: true
      deploy: true
      setup: true
      provision: true
    sys_repository_managers:
      flatpak: "{{ app_blender_application['type'] == 'flatpak' }}"
      snap: "{{ app_blender_application['type'] == 'snap' }}"
      git: "{{ app_blender_application['type'] == 'git' }}"
      pip: "{{ app_blender_application['type'] == 'pip' }}"
    sys_repository_catalog_distro: "{{ app_blender_repository_catalog_distro }}"
    sys_repository_catalog_yum: "{{ app_blender_repository_catalog_yum }}"
    sys_repository_catalog_apt: "{{ app_blender_repository_catalog_apt }}"
    sys_repository_custom_yum: "{{ app_blender_repository_custom_yum }}"
    sys_repository_custom_apt: "{{ app_blender_repository_custom_apt }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_repository"

- name: "Application / Blender / Prerequisite / Prepare archive manager"
  vars:
    bkp_archive:
      deploy: true
  ansible.builtin.include_role:
    name: "serdigital64.backup.bkp_archive"

- name: "Application / Blender / Prerequisite / Prepare package installer"
  vars:
    sys_package:
      prepare: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
