---
- name: "Application / FreeCAD / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ app_freecad_application | default('app_freecad_application') }})"
    quiet: true
    that:
      - app_freecad_application is defined
      - app_freecad_application | length > 0
      - app_freecad_application['name'] is defined
      - app_freecad_application['type'] is defined
      - app_freecad_application['version'] is defined
      - app_freecad_application['installed'] is defined

- name: "Application / FreeCAD / Deploy / Package"
  ansible.builtin.include_tasks:
    file: "app_freecad_deploy_package.yml"
  when:
    - app_freecad_application is defined
...
