---
- name: "Application / FreeCAD / Initialize"
  ansible.builtin.include_tasks:
    file: "app_freecad_initialize.yml"

- name: "Application / FreeCAD / Deploy"
  ansible.builtin.include_tasks:
    file: "app_freecad_deploy.yml"
  when:
    - app_freecad['deploy'] is defined
    - app_freecad['deploy']

- name: "Application / FreeCAD / Finalize"
  ansible.builtin.include_tasks:
    file: "app_freecad_finalize.yml"
...
