---
app_tilix_profiles:
  distro:
    latest:
      supported: true
      packages:
        - name: "tilix"

app_tilix_repository_custom_yum: []
app_tilix_repository_custom_apt: []

app_tilix_repository_catalog_distro: {}
app_tilix_repository_catalog_yum: {}
app_tilix_repository_catalog_apt: {}
...
