---
- name: "Application / Zoom / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_zoom_platforms

- name: "Application / Zoom / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_zoom_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_zoom"
    - app_zoom['resolve_prereq']
...
