---
- name: "Application / MS Teams / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_msteams_platforms

- name: "Application / MS Teams / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + app_msteams_os_family + '.yml' }}"
  changed_when: false

- name: "Application / MS Teams / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_msteams_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_msteams"
    - app_msteams['resolve_prereq']
...
