---
- name: "Application / OBS / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_obs_platforms

- name: "Application / OBS / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_obs_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_obs"
    - app_obs['resolve_prereq']
...
