---
dependency:
  name: "galaxy"
  options:
    ignore-errors: true
    role-file: "meta/requirements-dev.yml"
    requirements-file: "meta/requirements-dev.yml"
    collections-path: ${DEVAP_VAR_COLLECTIONS}
driver:
  name: ${DEVAP_MOLECULE_DRIVER}
provisioner:
  name: "ansible"
  log: ${DEVAP_TEST_DEBUG}
  ansible_args:
    - "${DEVAP_TEST_ANSIBLE_VERBOSE}"
  env:
    # Required to let molecule find installed collections in test environment
    ANSIBLE_COLLECTIONS_PATHS: ${ANSIBLE_COLLECTIONS_PATHS}
    ANSIBLE_COLLECTIONS_PATH: ${ANSIBLE_COLLECTIONS_PATH}
  options:
      vvv: ${DEVAP_TEST_DEBUG}
  config_options:
      ssh_connection:
        pipelining: yes
      defaults:
        allow_world_readable_tmpfiles: false
        keep_remote_files: false
        string_conversion_action: error
        gathering: explicit
        fact_caching: yaml
        transport: ssh
        any_errors_fatal: true
        error_on_undefined_vars: true
        system_warning: true
        invalid_task_attribute_failed: true
        deprecation_warnings: true
        action_warnings: true
        display_args_to_stdout: ${DEVAP_TEST_DEBUG}
        verbosity: ${DEVAP_TEST_ANSIBLE_VERBOSITY}
verifier:
  name: "ansible"
lint: |
  ${DEVAP_CMD_YAMLLINT} ${DEVAP_TEST_YAML_LINT_VERBOSE} ${DEVAP_TEST_ROLE_PATH} &&
  ${DEVAP_CMD_ANSIBLELINT} ${DEVAP_TEST_ANSIBLE_LINT_VERBOSE} -c ${DEVAP_ANSIBLE_LINT} --project-dir ${DEVAP_TEST_ROLE_PATH} --exclude molecule
platforms:
  - name: "centos8"
    image: "ghcr.io/serdigital64/centos-8-ansible-node:latest"
    pre_build_image: true
    groups:
      - "centos"
      - "centos_systemd"
      - "redhat"
      - "redhat_systemd"
      - "rhel"
      - "rhel_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "rhel8"
    image: "ghcr.io/serdigital64/rhel-8-ansible-node:latest"
    pre_build_image: true
    groups:
      - "ubi"
      - "ubi_systemd"
      - "redhat"
      - "redhat_systemd"
      - "rhel"
      - "rhel_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "almalinux8"
    image: "ghcr.io/serdigital64/almalinux-8-ansible-node:latest"
    pre_build_image: true
    groups:
      - "alm"
      - "alm_systemd"
      - "redhat"
      - "redhat_systemd"
      - "rhel"
      - "rhel_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "rockylinux8"
    image: "ghcr.io/serdigital64/rockylinux-8-ansible-node:latest"
    pre_build_image: true
    groups:
      - "rck"
      - "rck_systemd"
      - "redhat"
      - "redhat_systemd"
      - "rhel"
      - "rhel_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "oraclelinux8"
    image: "ghcr.io/serdigital64/oraclelinux-8-ansible-node:latest"
    pre_build_image: true
    groups:
      - "oel"
      - "oel_systemd"
      - "redhat"
      - "redhat_systemd"
      - "rhel"
      - "rhel_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "fedora33"
    image: "ghcr.io/serdigital64/fedora-33-ansible-node:latest"
    pre_build_image: true
    groups:
      - "fedora"
      - "fedora_systemd"
      - "redhat"
      - "redhat_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "fedora35"
    image: "ghcr.io/serdigital64/fedora-35-ansible-node:latest"
    pre_build_image: true
    groups:
      - "fedora"
      - "fedora_systemd"
      - "redhat"
      - "redhat_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "fedora36"
    image: "ghcr.io/serdigital64/fedora-36-ansible-node:latest"
    pre_build_image: true
    groups:
      - "fedora"
      - "fedora_systemd"
      - "redhat"
      - "redhat_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "debian10"
    image: "ghcr.io/serdigital64/debian-10-ansible-node:latest"
    pre_build_image: true
    groups:
      - "debian"
      - "debian_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "debian11"
    image: "ghcr.io/serdigital64/debian-11-ansible-node:latest"
    pre_build_image: true
    groups:
      - "debian"
      - "debian_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "ubuntu20"
    image: "ghcr.io/serdigital64/ubuntu-20.4-ansible-node:latest"
    pre_build_image: true
    groups:
      - "ubuntu"
      - "ubuntu_systemd"
      - "debian"
      - "debian_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "ubuntu21"
    image: "ghcr.io/serdigital64/ubuntu-21.4-ansible-node:latest"
    pre_build_image: true
    groups:
      - "ubuntu"
      - "ubuntu_systemd"
      - "debian"
      - "debian_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "ubuntu22"
    image: "ghcr.io/serdigital64/ubuntu-22.4-ansible-node:latest"
    pre_build_image: true
    groups:
      - "ubuntu"
      - "ubuntu_systemd"
      - "debian"
      - "debian_systemd"
      - "linux"
      - "linux_systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
...
