---
namespace: "serdigital64"
name: "application"
version: "2.1.0"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating office applications provisioning"
license:
  - "Apache-2.0"
tags:
  - "application"
  - "productivity"
  - "office"
  - "system"
dependencies:
  serdigital64.system: "*"
  serdigital64.backup: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
