---
- name: "Application / Firefox / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_firefox_platforms

- name: "Application / Firefox / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + ansible_distribution + ansible_distribution_major_version + '.yml' }}"

- name: "Application / Firefox / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_firefox_prerequisite.yml"
  when:
    - app_firefox['resolve_prereq'] is defined
    - app_firefox['resolve_prereq']
...
