---
- name: "Application / Firefox / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ app_firefox_application | default('app_firefox_application') }})"
    quiet: true
    that:
      - app_firefox_application is defined
      - app_firefox_application | length > 0
      - app_firefox_application['name'] is defined
      - app_firefox_application['type'] is defined
      - app_firefox_application['version'] is defined
      - app_firefox_application['installed'] is defined

- name: "Application / Firefox / Deploy / Package"
  ansible.builtin.include_tasks:
    file: "app_firefox_deploy_package.yml"
  when:
    - app_firefox_application is defined
...
