---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Setup application"
      vars:
        app_vscode:
          setup: true
        app_vscode_users:
          - name: "test1"
            home: "/home/test1"
            extensions:
              - "markdown"
              - "java"
          - name: "test2"
            home: "/home/test2"
            extensions:
              - "html"
              - "css"
      ansible.builtin.include_role:
        name: "app_vscode"
...
