---
galaxy_info:
  role_name: "app_pitivi"
  author: "serdigital64"
  description: "Manage provisioning of the Pitivi application"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "pitivi"
dependencies: []
...
