---
- name: "Application / X_TASK_ROLE_NAME_X / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_pinta_platforms

- name: "Application / X_TASK_ROLE_NAME_X / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + app_pinta_os_family + '.yml' }}"

- name: "Application / X_TASK_ROLE_NAME_X / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_pinta_prerequisite.yml"
  when:
    - app_pinta['resolve_prereq'] is defined
    - app_pinta['resolve_prereq']
...
