---
- name: "Application / X_TASK_ROLE_NAME_X / Initialize"
  ansible.builtin.include_tasks:
    file: "app_pinta_initialize.yml"

- name: "Application / X_TASK_ROLE_NAME_X / Deploy"
  ansible.builtin.include_tasks:
    file: "app_pinta_deploy.yml"
  when:
    - app_pinta['deploy'] is defined
    - app_pinta['deploy']

- name: "Application / X_TASK_ROLE_NAME_X / Finalize"
  ansible.builtin.include_tasks:
    file: "app_pinta_finalize.yml"
...
