---
- name: "Application / Pinta / Initialize"
  ansible.builtin.include_tasks:
    file: "app_pinta_initialize.yml"

- name: "Application / Pinta / Deploy"
  ansible.builtin.include_tasks:
    file: "app_pinta_deploy.yml"
  when:
    - app_pinta['deploy'] is defined
    - app_pinta['deploy']

- name: "Application / Pinta / Finalize"
  ansible.builtin.include_tasks:
    file: "app_pinta_finalize.yml"
...
