---
- name: "Application / LibreOffice / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_libreoffice_platforms

- name: "Application / LibreOffice / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_libreoffice_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_libreoffice"
    - app_libreoffice['resolve_prereq']
...
