---
- name: "Prepare"
  hosts: redhat-systemd
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        app_vscode:
          resolve_prereq: true
      ansible.builtin.include_role:
        name: "app_vscode"
...
