---
- name: "Application / Chrome / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application:
      name: "{{ app_chrome_application['name'] }}"
      type: "{{
        (app_chrome_application['type'] == 'native') |
        ternary(app_chrome_application_native, app_chrome_application['type'])
        }}"
      version: "{{ app_chrome_application['version'] }}"
      installed: "{{ app_chrome_application['installed'] }}"
    sys_package_profiles: "{{ app_chrome_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
