---
- name: "Application / Chrome / Initialize"
  ansible.builtin.include_tasks:
    file: "app_chrome_initialize.yml"

- name: "Application / Chrome / Deploy"
  ansible.builtin.include_tasks:
    file: "app_chrome_deploy.yml"
  when:
    - "'deploy' in app_chrome"
    - app_chrome['deploy']

- name: "Application / Chrome / Finalize"
  ansible.builtin.include_tasks:
    file: "app_chrome_finalize.yml"
...
