---
- name: "Application / KeePassXC / Setup / User / Configuration repository ({{
    app_keepassxc___setup_user['home'] + '/' + app_keepassxc_base['paths']['etc_keepassxc']
    }})"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ app_keepassxc___setup_user['home'] + '/' + app_keepassxc_base['paths']['etc_keepassxc'] }}"
    owner: "{{ app_keepassxc___setup_user['user'] }}"
    group: "{{ app_keepassxc___setup_user['user'] }}"
    mode: "{{ app_keepassxc_base['access']['mode']['dir'] }}"

- name: "Application / KeePassXC / Setup / User / Create default configuration ({{
    app_keepassxc___setup_user['home'] + '/' + app_keepassxc_base['etc']['keepassxc_ini'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    owner: "{{ app_keepassxc___setup_user['user'] }}"
    group: "{{ app_keepassxc___setup_user['user'] }}"
    mode: "{{ app_keepassxc_base['access']['mode']['file'] }}"
    src: "{{ app_keepassxc_base['templates']['keepassxc_ini'] }}"
    dest: "{{ app_keepassxc___setup_user['home'] + '/' + app_keepassxc_base['etc']['keepassxc_ini'] }}"
...
