---
- name: "Application / DrawIO / Initialize"
  ansible.builtin.include_tasks:
    file: "app_drawio_initialize.yml"

- name: "Application / DrawIO / Deploy"
  ansible.builtin.include_tasks:
    file: "app_drawio_deploy.yml"
  when:
    - "'deploy' in app_drawio"
    - app_drawio['deploy']

- name: "Application / DrawIO / Finalize"
  ansible.builtin.include_tasks:
    file: "app_drawio_finalize.yml"
...
