---
app_vscode_repository_custom_yum:
  - name: "vscode"
    description: "VSCode official RPM Repository"
    url: "https://packages.microsoft.com/yumrepos/vscode"
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
app_vscode_repository_custom_apt: []

app_vscode_repository_catalog_yum:
  vscode: true
app_vscode_repository_catalog_apt: {}
...
