---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Control service"
      vars:
        app_keepassxc:
          setup: true
        app_keepassxc_setup_users: "{{ test_app_keepassxc_setup_users }}"
      ansible.builtin.include_role:
        name: "app_keepassxc"
...
