---
# Define platform specific paths
app_firefox_base:
  paths: "{{ app_firefox_base_common['paths'] }}"
  etc: "{{ app_firefox_base_common['etc'] }}"
  files: "{{ app_firefox_base_common['files'] }}"
  run: "{{ app_firefox_base_common['run'] }}"
  templates: "{{ app_firefox_base_common['templates'] }}"
  access: "{{ app_firefox_base_common['access'] }}"

# Define application package details
app_firefox_profiles:
  snap: "{{ app_firefox_profiles_common['snap'] }}"
  flatpak: "{{ app_firefox_profiles_common['flatpak'] }}"
  distro:
    latest:
      supported: true
      packages:
        - name: "firefox-esr"

# Define custom package repositories
app_firefox_repository_custom_yum: []
app_firefox_repository_custom_apt: []

# Set package repositories states
app_firefox_repository_catalog_distro: {}
app_firefox_repository_catalog_yum: {}
app_firefox_repository_catalog_apt: {}
...
