---
- name: "Application / X_TASK_ROLE_NAME_X / Initialize"
  ansible.builtin.include_tasks:
    file: "app_pitivi_initialize.yml"

- name: "Application / X_TASK_ROLE_NAME_X / Deploy"
  ansible.builtin.include_tasks:
    file: "app_pitivi_deploy.yml"
  when:
    - app_pitivi['deploy'] is defined
    - app_pitivi['deploy']

- name: "Application / X_TASK_ROLE_NAME_X / Finalize"
  ansible.builtin.include_tasks:
    file: "app_pitivi_finalize.yml"
...
