---
- name: "Application / GIMP / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_gimp_platforms

- name: "Application / GIMP / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_gimp_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_gimp"
    - app_gimp['resolve_prereq']
...
