---
- name: "Application / GIMP / Initialize"
  ansible.builtin.include_tasks:
    file: "app_gimp_initialize.yml"

- name: "Application / GIMP / Deploy"
  ansible.builtin.include_tasks:
    file: "app_gimp_deploy.yml"
  when:
    - "'deploy' in app_gimp"
    - app_gimp['deploy']

- name: "Application / GIMP / Finalize"
  ansible.builtin.include_tasks:
    file: "app_gimp_finalize.yml"
...
