---
app_chrome_base:
  run:
    google_chrome: "/usr/bin/google-chrome"

app_chrome_application_native: "rpm"

app_chrome_profiles:
  rpm:
    latest:
      supported: true
      origin: "https://dl.google.com/linux/direct"
      packages:
        - file: "google-chrome-stable_current_x86_64.rpm"
          name: "google-chrome-stable"

app_chrome_repository_custom_yum: []
app_chrome_repository_custom_apt: []

app_chrome_repository_catalog_distro: {}
app_chrome_repository_catalog_yum: {}
app_chrome_repository_catalog_apt: {}
...
