---
- name: "Application / Spotify / Initialize"
  ansible.builtin.include_tasks:
    file: "app_spotify_initialize.yml"

- name: "Application / Spotify / Deploy"
  ansible.builtin.include_tasks:
    file: "app_spotify_deploy.yml"
  when:
    - "'deploy' in app_spotify"
    - app_spotify['deploy']

- name: "Application / Spotify / Finalize"
  ansible.builtin.include_tasks:
    file: "app_spotify_finalize.yml"
...
