---
app_shotcut_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_shotcut_profiles:
  snap:
    latest:
      packages:
        - name: "shotcut"
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "org.shotcut.Shotcut"
...
