---
- name: "Application / VSCode / Usage example"
  hosts: "localhost"
  gather_facts: true
  vars:
    test_user: "testusr64"
    test_home: "/home/testusr64"

  pre_tasks:
    - name: "Create test user"
      vars:
        sys_user:
          setup: true
        sys_user_accounts:
          - name: "{{ test_user }}"
            home: "{{ test_home }}"
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_user"

  tasks:
    - name: "Example: Install VSCode"
      vars:
        app_vscode:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_vscode"

    - name: "Example: Configure VSCode for the user {{ test_user }}"
      vars:
        app_vscode:
          setup: true
        app_vscode_users:
          - name: "{{ test_user }}"
            home: "{{ test_home }}"
            extensions:
              - "markdown"
              - "java"
      ansible.builtin.include_role:
        name: "serdigital64.application.app_vscode"
...
