---
- name: "Application / Pitivi / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Pitivi"
      vars:
        app_pitivi:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_pitivi"
...
