---
- name: "Application / ShotCut / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install ShotCut"
      vars:
        app_shotcut:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_shotcut"
...
