---
- name: "Application / Skype / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Skype"
      vars:
        app_skype:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_skype"
...
