---
- name: "Application / Firefox / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Firefox"
      vars:
        app_firefox:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_firefox"
...
