---
- name: "Application / Spotify / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Spotify"
      vars:
        app_spotify:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_spotify"
...
