---
- name: "Application / Blender / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Blender"
      vars:
        app_blender:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_blender"
...
