---
- name: "Application / Tilix / Prepare / Paths / Create"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ app_tilix___prepare_path }}"
    owner: "{{ app_tilix_base['access']['user']['owner'] }}"
    group: "{{ app_tilix_base['access']['group']['owner'] }}"
    mode: "{{ app_tilix_base['access']['mode']['dir'] }}"
  loop:
    - "{{ app_tilix_base['paths']['var'] }}"
  loop_control:
    loop_var: "app_tilix___prepare_path"
...
