---
- name: "Application / InkScape / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_inkscape_platforms

- name: "Application / InkScape / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_inkscape_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_inkscape"
    - app_inkscape['resolve_prereq']
...
