---
- name: "Application / VSCode / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_vscode_platforms

- name: "Application / VSCode / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + app_vscode_os_family + '.yml' }}"

- name: "Application / VSCode / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_vscode_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_vscode"
    - app_vscode['resolve_prereq']
...
