---
- name: "Application / VSCode / Setup / Extensions / Create recommended extensions (user: {{ app_vscode___setup_user['name'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ app_vscode___setup_user['name'] }}"
    group: "{{ app_vscode___setup_user['name'] }}"
    mode: "{{ app_vscode_base['access']['mode']['file'] }}"
    src: "{{ app_vscode_base['templates']['extensions'] }}"
    dest: "{{
      app_vscode___setup_user['home'] + '/' +
      app_vscode_base['paths']['etc_user'] + '/' +
      app_vscode_base['files']['user_extensions']
    }}"
...
