---
- name: "Application / VSCode / Setup / Preferences / Create configuration path (user: {{ app_vscode___setup_user['name'] }})"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    owner: "{{ app_vscode___setup_user['name'] }}"
    group: "{{ app_vscode___setup_user['name'] }}"
    mode: "{{ app_vscode_base['access']['mode']['dir'] }}"
    path: "{{
      app_vscode___setup_user['home'] + '/' +
      app_vscode_base['paths']['etc_user']
    }}"

- name: "Application / VSCode / Setup / Preferences / Create initial preferences (user: {{ app_vscode___setup_user['name'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    owner: "{{ app_vscode___setup_user['name'] }}"
    group: "{{ app_vscode___setup_user['name'] }}"
    mode: "{{ app_vscode_base['access']['mode']['file'] }}"
    src: "{{ app_vscode_base['templates']['settings'] }}"
    dest: "{{
      app_vscode___setup_user['home'] + '/' +
      app_vscode_base['paths']['etc_user'] + '/' +
      app_vscode_base['files']['user_settings']
    }}"
...
