---
- name: "Application / VSCode / Prepare package managers"
  vars:
    sys_repository:
      prepare: true
      deploy: true
      setup: true
      provision: true
    sys_repository_managers:
      flatpak: "{{ app_vscode_application['type'] == 'flatpak' }}"
      snap: "{{ app_vscode_application['type'] == 'snap' }}"
    sys_repository_catalog_yum: "{{ app_vscode_repository_catalog_yum }}"
    sys_repository_catalog_apt: "{{ app_vscode_repository_catalog_apt }}"
    sys_repository_custom_yum: "{{ app_vscode_repository_custom_yum }}"
    sys_repository_custom_apt: "{{ app_vscode_repository_custom_apt }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_repository"

- name: "Application / VSCode / Prepare package installer"
  vars:
    sys_package:
      prepare: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
